### ISSUE TITLE
Remove text-decoration: underline on click for action buttons

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#114]

**Comment by abziegler** [comment]
![h2o-action-buttons](https://user-images.githubusercontent.com/2140548/39430169-17f93fa0-4c5b-11e8-8abc-9d128242515f.png)

**Comment by abziegler** [comment]
onclick these button labels are showing text-decoration: underline. They shouldn't.

**Comment by rebeccacremona** [comment]
Whoops. I think I doubled-down on this behavior when working on action button accessibility. I thought that the underline should always appear on hover and focus, because I thought the resizing of the icon was easy to miss while I was zoomed in. If you hate it, maybe we can come up with something else for these? If we add an svg icon library (like Font Awesome) to H2O, there will be more design options/flexibility for these icons.

**Comment by abziegler** [comment]
Raise or fold, they say. @rebeccacremona has raised! Closing issue.
