### ISSUE TITLE
Export: items with no Word style applied; Block quotes

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#123]
Using this casebook's export as an example: https://h2o-dev.lil.tools/casebooks/30540-federal-budget-policy-january-2016-playlist-26271/
there are a few items without Word styles applied to them. (Note you can use Advanced Find and Replace to search for styles) -
1) Certain lines in the case headers have no style applied: needing the "case header" style applied to them.
2) Certain cases that have centered headers (either roman numberals or letters) are "Normal" style instead of Resource Text style. (ex. Bowsher v Synar)
3) Block quotes! These generally only have "Normal" style applied to them, need Block Quote style applied across the board to them.

**Comment by bjohnson747** [comment]
<img width="519" alt="bowsner v synar" src="https://user-images.githubusercontent.com/12850389/29690619-b35a701a-88f5-11e7-890d-ec5b8afda5ea.png">

**Comment by bjohnson747** [comment]
I'm still getting "Normal" word style on block quotes on this document: https://h2o-dev.lil.tools/casebooks/30540-federal-budget-policy-january-2016-playlist-26271/

Also getting it (Normal style) in the first line of the
 _[Party]
v.
[Party]_
case headings.

 I think you mentioned having an issue applying this (a 'case header' style that catches the parties, court, decision date etc at the top of a case) as a Word style, i wanted to double-check on that; I know that's something that was able to be worked out in the export in H2Ov1 so wanted to be sure we understood any further complications with that in the new H2O.

**Comment by emmalemma** [comment]
Hmm, I outsmarted myself with a CaseHeader that only applies to the _first_ case in the casebook. Should be working now.

The issue isn't applying the Word style, just knowing where the header is. There's no semantic information about the case header, it's just an initial group of <center> tags. 

We're applying the CaseHeader style there, but it's not perfect— e.g. one of these cases has a centered section heading immediately after the case header, so it gets the style too. Without intelligence about what a case header looks like, it can't tell the difference.

Especially for new content, I think it would make more sense to tag the header in the case itself rather than trying to do that on the fly.

**Comment by bjohnson747** [comment]
Cool, these all are looking better! Block quotes and in-case headers; a bunch of the case headers too are applying, especially in that federal budget policy casebook.

So i know for future reference; the main item that's used for the export to know what to apply the Case Header style to is the presence of the center tag @ the top of a case, yes? 
(This will help me understand what times the case header is applied correctly to cases and times it's not)
Thanks!

**Comment by emmalemma** [comment]
Yep, that's correct. If the first tag in the case is `<center>`, it and the immediately following center tags will be CaseHeader. `<center>` tags that appear after any other tag will just be Centered style.
