### ISSUE TITLE
Add date info to Casebooks

### ISSUE THREAD

**Issue by cath9** [harvard-lil/h2o#1303]
Perhaps Year Published and then also a last updated date? 

(note that I see this in the search area, but not when viewing a casebook)

**Comment by lizadaly** [comment]
@cath9 How's this?

If published and modified more recently than when it was published:

<img width="808" alt="image" src="https://user-images.githubusercontent.com/19571/200937555-2dbdbb40-3540-406f-8b91-7b76e27f324c.png">

If published and not modified since then:

<img width="811" alt="image" src="https://user-images.githubusercontent.com/19571/200937591-f4a14274-e5fe-4a36-b97b-437dc55ab1df.png">

If not published, nothing is displayed.

**Comment by lizadaly** [comment]
Probably better to see in the context of the full page:

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/19571/200937726-427369e6-1afa-48b6-b96d-191c9cd4f74c.png">

**Comment by lizadaly** [comment]
<img width="862" alt="image" src="https://user-images.githubusercontent.com/19571/200938891-dc14d656-cc37-4395-af6b-4368529eb527.png">
