### ISSUE TITLE
Make an ideal docx example export

### ISSUE THREAD

**Issue by holtchesley** [harvard-lil/h2o#1427]
Use the examples from #1422 to craft a docx that can serve as a template for exports.

**Comment by holtchesley** [comment]
- Roman numerals for non-numbered sections preceding numbered sections (Preface, Foreward, Introduction). 
- Casebook Headnote becomes block (prior to TOC) or preface?
- Footnotes, no endnotes.

**Comment by rebeccacremona** [comment]
More verbiage, from Slack:
> 1) Make us a gorgeous DOCX casebook (https://github.com/harvard-lil/h2o/issues/1427), with all the bells and whistles, informed by aesthetics, printing conventions, Jordi's feedback about our DOCX export and the PDF of JZ's book, and maybe https://github.com/harvard-lil/h2o/issues/1422, using the Microsoft Word GUI.
>
> 2) Then, changing https://github.com/harvard-lil/h2o/blob/develop/services/pandoc/reference_docx/word/styles.xml until the styles are present that are necessary for said gorgeous casebook. And, learning how to add all the other features and change all the necessary settings using a combo of python-docx (where supported) and plain old etree/lxml (per CAPnow example, and etc.). https://github.com/harvard-lil/h2o/pull/1467 may be useful too.
>
> These will help us make an objectively better exported casebook docx.
>
> There's a hope that this will speed up the docx -> indesign process for MIT press books, with the assistance of macros.

Link to the thread in Slack re: feedback https://hlslil.slack.com/archives/C4FE9FL56/p1635180657021800

**Comment by ChefAndy** [comment]
## Andy's Checklist

- **Visuals**
  - [x] Get basic headline and body text style, visual hierarchy, letter/line spacing, space relationships styles squared away
  - [x] Make the TOC more readable
  - [x] Restyle introductory page
  - [x] Get footers set up
      - [x] Styled? 
      - [x] Final Layout
      - [x] Different Visual Presentations hooked up to different tracks
          - [x] put together a couple of style options
          - [x] styling elements like font weights, etc.
  - [x] Headers
      - [x] Dynamic?
      - [x] Styled? 
      - [x] Change style with sections (e.g. _i, ii, iii_ for frontmatter and 1, 2, 3 for content) 
      - [x] Final Layout 
- **Structure**
  - [x] Set up the style cascades to make customization easier  
example) when the template is applied in word. 
  - [x] Apply the template to a few sample case books to make sure the basics work
  - [x] Headlines should inherit the font style of its parent paragraph and only specify the size of the type. (SURE WOULD BE NICE if Word supported percentage font sizes like OOXML specifies.)
-**Pandoc Implementation**
      - [x] Compare Pandoc styles w/mine and investigate discrepancies
          - [x] Figure out why things adopt facets from other styles (a color, or numbering style, for 
  - [x] Install
    - [x] `unreadable content` trying to make new word docs from new styles in old template. 
       * content doesn't render, but most if not all styles seem to show up fine.
       * [x] try opening in python-docx to see what the deal is
       * [x] maybe pandoc would have better errors?
  - [x] Test & Test Some More
- **HTML Edits**
  - [x] Add data-custom-styles attribute to acknowledgement/credits area rather than using generic h1/etc.
  - [x] Add chapter header, etc. data-custom-style to top-level section
  - [x] Add `<div data-custom-style="invisibleseparator">&nbsp;</div>` (or similar) under chapter, section and resource header blocks
  - [x] See why chapter div isn't working— use len() of ordinal if need be
  - [x] Move casebook headnotes to internal front matter page with an H Struct 2 level headline style and a more sane body text size. Maybe keep it on the front if it's shorter than X characters?
  - [ ] Move style instructions to internal front matter page
- **XML**
- [ ] Clean up DefaultParagraphFont character style dependencies
   - [ ] Update docs to adjust
- [ ] Change style order and move style documentation notes to be inline like they are now

## [ ] PR 🚀

- Post
 - [ ] get section separators up-and-running with python-docx (or something)
