### ISSUE TITLE
Right-aligned text in some footnotes of a CAP case

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/h2o#1439]
https://opencasebook.org/documents/5077/

Check out these funny-looking, right-aligned footnotes:

![image](https://user-images.githubusercontent.com/11020492/138330657-4185b437-4d13-4d13-a02b-29564a3c913d.png)

![image](https://user-images.githubusercontent.com/11020492/138330953-590e3367-cf85-4455-921b-60d9430036a8.png)

Example markup (looks fine)
```
<aside id="footnote_1_22" class="footnote" data-label="2">
  <a href="#ref_footnote_1_22">2</a>
  <p id="p-160">
    <em>See</em> <em>Bubolz v. Dane Cty.</em>, <a class="citation" href="https://cite.case.law/wis-2d/159/284/#p294" data-index="127" data-case-ids="8667287">159 Wis. 2d 284</a>, 295-96, <a class="citation" href="https://cite.case.law/wis-2d/159/284/#p294" data-index="128" data-case-ids="8667287">464 N.W.2d 67</a> (Ct. App. 1990) (injunction against violation of restrictive covenant did not prohibit a residents from engaging in business activities that are "incidental to their occupation of the premises as their single family residence."); <em>see also</em> <em>Joyce v. Conway</em>, <a class="citation" href="https://cite.case.law/wis-2d/7/247/#p251" data-index="129" data-case-ids="8677350">7 Wis. 2d 247</a>, 251, <a class="citation" href="https://cite.case.law/citations/?q=96%20N.W.2d%20530" data-index="130">96 N.W.2d 530</a> (1959) (explaining that acquiescence to past violations does not deprive affected property owners of the right to enforce later violations of a restrictive covenant).
  </p>
</aside>
```
(I also note that the last 3 notes on the page don't have matching footnotemarks; this looks to be an issue in [CAP](https://cite.case.law/nw2d/914/643/#footnote_1_23) too, so likely unrelated/not an H2O issue)

**Comment by dongkyunc** [comment]
[Looks like the selector is a bit broad here.](https://github.com/harvard-lil/h2o/blob/develop/web/frontend/styles/cases.scss#L55-L57) Changing the selector from `aside.footnote a` to `aside.footnote > a` so that it only catches the anchor pointing back to the body text and not the links in the footnote text itself should do the trick. 

Apologies for not making a PR but my current machine is a bit too weak to comfortably build and test. However, playing with the style editor does seem to indicate that this is a working solution.
<img width="1392" alt="Screen Shot 2021-11-25 at 9 32 37 PM" src="https://user-images.githubusercontent.com./8096144/143532227-4d5f82de-31f3-4849-a9c8-f68bed87e694.png">

**Comment by lizadaly** [comment]
This was fixed in the linked PR!
