### ISSUE TITLE
Empty search results on first try; query string weirdness

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/h2o#1442]
1. Visit https://opencasebook.org/search/
2. Enter a casebook title keyword (e.g. torts) or author's surname (e.g lessig)
3. Hit enter/click submit. "No results found", URL includes `school=None` (e.g. `https://opencasebook.org/search/?type=casebooks&q=torts&sort=display_name&author=&school=None` or `https://opencasebook.org/search/?type=casebooks&q=lessig&sort=display_name&author=&school=None`)
4. Hit enter/click submit again, without changing anything. Results found, URL ends at `&school=` (e.g. `https://opencasebook.org/search/?type=casebooks&q=torts&sort=display_name&author=&school=` or `https://opencasebook.org/search/?type=casebooks&q=lessig&sort=display_name&author=&school=`)

**Comment by dongkyunc** [comment]
This is (probably) happening because certain casebooks entries have incorrect properties.

The behavior is likely as follows:
1. The search URL is visited, with no query parameters. No filters are thus provided and so all the casebooks are returned. Some of these do not have an appropriate affiliation fields or no value at all and thus, [`{% if request.GET.school == school %}selected {% endif %}`](https://github.com/harvard-lil/h2o/blob/4e0ad9597fb2860296da060195528e8cd79391e7/web/main/templates/search/filters.html#L24) is firing. The screenshots below confirm that.
2. That filter value is used for the next search, but coerced as the string `"None"`, which would match no casebook entry, thus returns no results.
3. Since now the offending malformed entry is no longer being returned, the `"None"` option can no longer be selected and this query returns as expected.

A quick solution would be to change the linked line to `if request.GET.school and request.GET.school == school`. 

However, there is a deeper issue: The values in the database are occasionally junk. [Three casebooks ](https://opencasebook.org/search/?type=casebooks&q=&sort=display_name&author=&school=,%20) are affiliated with the `,` school and multiple other schools have multiple entries with slight variations in either spelling or formatting. I don't have much visibility into how the affiliations are created so I'm not sure what possible solutions there would look like. 

<img width="535" alt="image" src="https://user-images.githubusercontent.com/8096144/143539965-9ab27a6d-9489-484a-b971-75def6ef6ae7.png">
<img width="416" alt="image" src="https://user-images.githubusercontent.com/8096144/143540210-b963b05a-b581-454a-82ac-c97e6362c503.png">

**Comment by lizadaly** [comment]
This particular original issue no longer occurs.
