### ISSUE TITLE
Search results UX: seeming duplicates

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/h2o#1471]
I, without outside context, cannot right now distinguish between some very similar-seeming casebooks:
![image](https://user-images.githubusercontent.com/11020492/144288946-191a2908-b0d9-4ad0-b4af-ce40672a1057.png)

E.g., https://opencasebook.org/casebooks/246/ and https://opencasebook.org/casebooks/715/, published one day apart, where the authors are in a different order but to my eye seem otherwise the same. Both are available publicly.

I bet this is confusing for other visitors as well. Is this a UI thing (the distinguishing factor is not prominent), or a data thing (there shouldn't be both)?

**Comment by lizadaly** [comment]
Implementing https://github.com/harvard-lil/h2o/issues/1349 will help with this, but only if the professor has actually done the work of grouping. 

The particular case of 246 and 715 seems unavoidable–if the same user publishes near-identical books, I think our best choice would be to reach out to them and ask if the duplication is intentional. Maybe they're trying to do something interesting!

**Comment by lizadaly** [comment]
This was mostly resolved by #1973
