### ISSUE TITLE
Autohide export modal after successful export/download

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#151]
![h2o - export modal](https://user-images.githubusercontent.com/2140548/30485671-270dd922-99fc-11e7-8ea3-5cfe2d6d79c0.png)

**Comment by rebeccacremona** [comment]
Since, for the time being, there are no choices to be made here (one export format only), this PR (https://github.com/harvard-lil/h2o/pull/377) makes the export button trigger download immediately, with no intervening modal.

If, later, the ability to pick between multiple formats is added, and a modal is needed again, agreed, dismissing it after download is initiated sounds right. Make sure keyboard focus is returned to the action button when the modal is dismissed.
