### ISSUE TITLE
Add additional informative text to key buttons on the Casebook page

### ISSUE THREAD

**Issue by lizadaly** [harvard-lil/h2o#1566]
In `Casebook.vue` and other front-end pages, add `title` attributes to the various buttons like "Save", "Publish", etc. with short phrases adding context to the button where the behavior could be expanded on.  

If you aren't sure what to put or what the button does, ask the team since that means it's not obvious and is a good candidate!

**Comment by rebeccacremona** [comment]
Since `title` attributes aren't great from an accessibility standpoint, I'd love for us to have a think about whether an alternative would work with the design. In the spirit of not letting the perfect stand in the way of the good, we could do incrementally with `title`s right away swap in something else later.

**Comment by lizadaly** [comment]
You're totally right, I wasn't caught up on the current best practices here. As a sighted desktop user wielding a mouse-pointer, I have been stymied by the purpose of some of the buttons ("Cancel" when I haven't initiated an action yet?) and my first instinct was to hover. I think your suggestion is a good one.

**Comment by rebeccacremona** [comment]
> "Cancel" when I haven't initiated an action yet?

Totally!!

**Comment by shljessie** [comment]
I was thinking of marking places that I think need edits with the title attribute & adding comments in the github issue page or a pr request??
