### ISSUE TITLE
Allow adding, replacing, and remove a book cover image

### ISSUE THREAD

**Issue by lizadaly** [harvard-lil/h2o#1579]
To differentiate titles, provide a sense of ownership, and support professors in promotion and branding, allow uploading a book cover image.

* Review any previous discussions on book cover images. Is there a reason this feature was not previously implemented?
* Consider copyright implications.
* Allow previewing the book cover during the creation process. 
* Allow admins to remove cover images.

**Comment by rebeccacremona** [comment]
Update on the status of this feature:

I added limited support for adding cover images in #1630 and #1635; Seonghee added support for displaying them in #1664. 

But, the feature is still disabled in production because as [Liza noticed](https://github.com/harvard-lil/h2o/pull/1664#issuecomment-1201652016), I didn't consider drafts/revisions or clones:

- Cover image needs to be added to the [revision merging process](https://github.com/harvard-lil/h2o/blob/develop/web/main/models.py#L3894)

- We might want to reconsider the paths at which I'm saving the images, which right now is by casebook ID... if not, we will need to change the image filename during the merging process, so that it has the ID of the published book, not the id of the temporary clone

- I didn't include any logic for clones. I think that means that, if the parent book's cover image gets updated, so does the cover image of all the children. We need to arrange for the file to be duplicated when cloning, so that each book points to its very own file.
