### ISSUE TITLE
Investigate the feasibility of replacing the text editor with https://waxjs.net/

### ISSUE THREAD

**Issue by lizadaly** [harvard-lil/h2o#1585]
The existing WYSIWYG editor is showing its age. Investigate whether a more modern tool would provide a better editing experience.

The investigation doesn't need to be confined to Wax; there may be others.

**Comment by emilyteng1008** [comment]
1. Can it be used to just format a short bit of content rather than a whole book?
2. Does it provide similar formatting tools to what our existing editor has?
3. Can you control which tools are available?
4. What software license does it use?
5. Are there examples of it being used that might be similar to our use case?

Options I looked into: 
**WAX**
1. Yes, it is very customizable, you can place it [anywhere](https://waxjs.net/docs/building_an_editor/) according to our layout. 
2. Yes, in addition to existing formatting tools, it also has the potential to include a suggestion mode, which is its central benefit. 
3. Yes, all the tools are available in its [documentation](https://waxjs.net/docs/wax/#available-editor-properties--toolgroups-and-services)
4. Permissive (MIT License) 
5. Yes, the creator Adam said that WAX is embedded in a lot of other coko projects 

**ProseMirror**
1. this is the library that WAX is built against, so it is very customizable to our needs 
2. Yes, it also offers features for [collaborative editing](https://prosemirror.net/docs/guide/#collab), where multiple people can work on the same document in real-time. It can also [track changes](https://prosemirror.net/examples/track/). 
3. [Yes](https://prosemirror.net/examples/menu/), you can also add plug ins 
4. Permissive (MIT License) 
5. Some [examples](https://discuss.prosemirror.net/t/who-is-using-prosemirror/1230) that use ProseMirror include [Dovetail](https://dovetailapp.com/), [Edition Unik](https://www.edition-unik.ch/), [SciFlow](https://www.sciflow.net/en/)

**Summernote**
1. [Yes](https://summernote.org/getting-started/#integration)
2. Yes
3. [Yes](https://summernote.org/deep-dive/), with lots of [plugins](https://github.com/summernote/awesome-summernote) 
4.  Permissive (MIT License) 
5. There are a lot of websites that use this, but I haven't found a use case similar to ours

Alternatively to replacing: 
The current rich-text editor we use is TinyMCE v5. I think it already has a lot of possibilities if we [upgrade](https://www.tiny.cloud/docs/tinymce/6/upgrading/) it to the latest version. It also offers a lot of [features](https://www.tiny.cloud/docs/tinymce/6/plugins/) we can customize.

**Comment by lizadaly** [comment]
This analysis is terrific! I didn't know about Summernote at all.

I haven't spent much time looking at the editor or the experience there, and haven't looked closely for specific feedback about it. I'd be very interested in your thoughts on what we should be looking to improve, since it seems like we have a lot of options with tooling.

**Comment by emilyteng1008** [comment]
I think a cool upgrade to our existing text editor is the **suggestion and track changes** feature that some of these options provide.

**Comment by emilyteng1008** [comment]
From my conversation with Adam: 

- Source formatting is a complex part to maintain, but because WAX editor is built off of ProseMirror, it maintains the source very well 
- Wax has a lot of use cases, and suggestion and track changes mode comes with the editor 
- He suggests not choosing an editor that is not based on ProseMirror because other ones don't have the same level of control over the result and source. 
- Wax is good because it is open-sourced and can help with implementation 
- He also sent me the coko foundation 2021-2022 annual report: https://coko.foundation/images/uploads/Coko_2021-2022_Annual_Report.pdf

**Comment by lizadaly** [comment]
This is great, sounds like we should pursue this! My guess is that it'll take some time, so this might be a thing for someone to iterate on in parallel to more immediately useful changes that we could finish in the next month or so. 

I really appreciate the work you did to explore this!
