### ISSUE TITLE
Add a formal User field of "institution"

### ISSUE THREAD

**Issue by lizadaly** [harvard-lil/h2o#1684]
We'd like to keep the `affiliation` field open-ended (though maybe add auto-suggest as recommended in #1651 to limit sprawl) and add a formal `institution` field that we'll control.

A few questions to sort out:

* Can a user belong to more than one institution? This has big implications for the implementation—once we decide they can only belong to a single institution it's hard to change, but allowing multiple introduces more complexity. However, if the reality is that many professors teach in multiple institutions over some unit period of time, it's probably worth implementing that way.
* Do we need to track institutional membership over time? If so, that also introduces more complexity, but needs to be captured up-front. If it's important to ask "how many professors published casebooks from HLS in 2022" we'll need to capture this longitudinally rather than just relying on the current value of the field.

*Definition of done:*

* A `User` can belong to zero or one (or more) institutions (see above)
* `institution` is added to the admin list and change views and to the CSV export for professor reports
* If present, the `institution` field appears on the user's public dashboard page.
* If present, it appears in the search results list somewhere (next to the author name in parentheses?)

*How we'll populate it*

* Propose we generate a list of law schools and any other orgs we want to feature in the list.
* The list of allowable institutions is populated in the Django admin (ideally the admin will allow pasting in a list of newline-delimited items rather than forcing us to create a zillion items one at a time)
* Users can update their institution from the populated dropdown and, if none applies, they're directed to fill out `affilitation`.

We may or may not pre-populate institutions for known users.

Would it be madness to try to capture logos/seals for some or all institutions? We could display them on the user's profile page. (We don't need to decide this up-front.)

**Comment by cath9** [comment]
@lizadaly I think one institution is good, and if they are related to other institutions they can add that to the affiliation field. I don't think we need retrospective info on the field. One thing to consider (in issue #1758) is having the personal institutions and affiliations on the author's profile, and then allowing them to designate a different "course institution" on each casebook. If we did that, I think the field would default to the professor's home institution, but be able to be changed. I think this would make it a bit clearer from the student/reader perspective, and also allow us to show "all courses taught at Harvard Law", capturing courses taught by people who may have since moved on. 

Occasionally we grant access to international institutions by adding domains to Django. During that process we input the name of the institution associated with the domain - would be cool if doing that added that institution to the drop down.

**Comment by cath9** [comment]
This spreadsheet has a list of institution names, along with data for other descriptive fields we've talked about adding like resource type and topics. I think we'll need to work out how we go about applying this to existing profiles, and also a process for adding schools to the list. 

https://docs.google.com/spreadsheets/d/1OOpsVo0eyJjkPDhVeRHNho0maUbZohIe2twoI_xnKDI/edit#gid=0

**Comment by lizadaly** [comment]
I think this wants to be its own model, which will make it easier to update in bulk. but also make it possible to add metadata—for example canonical URLs or logos that apply to each institution.

**Comment by lizadaly** [comment]
@cath9 Do you want to merge the current list of universities in the email whitelist into this list? It seems like eventually we could just get rid of the Email Whitelist model entirely.
