### ISSUE TITLE
Vue unit test suite cannot be upgraded past 1.0.0-beta.29

### ISSUE THREAD

**Issue by lizadaly** [harvard-lil/h2o#1962]
https://github.com/vuejs/vue-test-utils is pinned at a beta version from February, 2019. Upgrading to any of the 1.x release versions causes multiple test failures. (The 1.x line targets Vue 2 and is still actively maintained.)

Although test harnesses aren't user-facing, it's valuable to maintain and expand test coverage even for projects in maintenance mode—tests make it possible to safely iterate on software that is touched only occasionally, or with incomplete information. 

The failing tests are mostly around whitespace handling—this is important for the annotation code, so it's good that there are tests for this, but it's possible that the tests rely on side effects of the beta test harness and should be rewritten.

**Comment by leppert** [comment]
Oh the days. I wrote most of this back in 2019. Happy to answer questions from what I can remember. I do recall the whitespace struggles but my recollection was that they had to do with Vue core's handling rather than the test harness, but who knows. It does seem telling that this doesn't involve updating Vue but rather just the test harness.

**Comment by rebeccacremona** [comment]
> Oh the days.

![image](https://user-images.githubusercontent.com/11020492/229152057-8363270d-c441-45b2-9067-89cf8e46427a.png)
![image](https://user-images.githubusercontent.com/11020492/229152089-cd7e80b2-bf99-45a3-9623-f124264f1723.png)
![image](https://user-images.githubusercontent.com/11020492/229152312-f42b2383-6a91-4ce1-848b-5759fe411a52.png)
