### ISSUE TITLE
Reporting: Casebooks published by Verified Professors segmented by year

### ISSUE THREAD

**Issue by cath9** [harvard-lil/h2o#1978]
Looking to know how many casebooks were published by a verified professor in a given year. This should not be cumulative - just looking for a discrete number for each year. Ideally it will only include the first time a professor clicked "publish", and not include the publication of revision drafts.

**Comment by lizadaly** [comment]
We can't pull real revision drafts cumulatively because the publish edit log only goes back to 2021. Before that I can only tell you when the casebook was first created, not when it was first published, so I'll have to use "first-created" dates for all values.

**Comment by lizadaly** [comment]
Revised this: it looks like the edit log was backfilled, so while published dates prior to 2021 are estimates based on the status of the casebook at the time, after that they should be reliable, so I will use the edit log here.

(In other words, before 2021, we can't track when a book was published-then-unpublished here, but after 2021 this report should include casebooks that were since unpublished, or published in a different year than they were first created.)
