### ISSUE TITLE
Reporting: add cumulative totals for Verified Professors with Published casebooks

### ISSUE THREAD

**Issue by cath9** [harvard-lil/h2o#1979]
Looking to know the number of Verified Professors in the platform with published casebooks in any given year. 

This should be cumulative. i.e if in 2012, 5 verified professors published casebooks through the platform, and those all remained published in 2013 and also 6 more verified professors published casebooks in 2013, then the numbers I'm looking for would be:
2012 = 5
2013 = 11

Thanks!

**Comment by lizadaly** [comment]
It's surprisingly hard to know when a casebook was unpublished, because for some reason that state is not recorded in the edit log (it does record "first published").

I can tell if a casebook is _currently_ unpublished, but e.g. if I published in 2012, unpublished in 2013, then republished in 2023, there's no way to know that it was unpublished for the intervening 10 years.

There are only ~16 casebooks by professors that were ever published and are now unpublished (out of 417 casebooks ever published by verified professors). If it's important to drop those 16 somewhere in this report, I might be able to provide a guesstimate about which year they dropped out, but it wouldn't be accurate.
