### ISSUE TITLE
<section> & <article> tags cause casebooks to be unable to export

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#310]
* Text blocks with an < article> tag are causing Word to not be able to open them
* Cases with a < section> tag still in the case-text html prevent successful export

**Comment by cgruppioni** [comment]
Brett compile list of corrupt resources

**Comment by abziegler** [comment]
By 6/21 @bjohnson747 will post list of formatting problems that are corrupting data. May not be comprehensive but will have everything we've identified to date

**Comment by abziegler** [comment]
This is connected to https://github.com/harvard-lil/h2o/issues/371, which looks to be one example of misformatted cases

**Comment by bjohnson747** [comment]
**Findings to date**

_Export failures_
1. Text blocks with an < article> tag are causing Word to not be able to open them. This text block contains that tag: https://alpha.opencasebook.org/casebooks/65582-contracts-reading-group-for-export-only/sections/4.3-unconscionability - when i removed this tag, Word was able to open successfully.
(In this text block, the specific tags were: < article about="/ucc/2/2-302" typeof="sioc:Item foaf:Document" data-p-idx="1">  and < /article>

2. Cases with a < section> tag still in the case-text html prevent successful export. Ex., this case (https://alpha.opencasebook.org/cases/7958) included two sets of < section> < /section> tags. 
<img width="571" alt="screen shot 2018-06-20 at 6 34 00 pm" src="https://user-images.githubusercontent.com/12850389/41688165-feaefebe-74b8-11e8-95d9-df69864475d3.png">
Once I removed these, export was successful.



3. Need some help troubleshooting this. This casebook has the problem text block I mentioned above, https://alpha.opencasebook.org/casebooks/68805-sam-contracts-for-testing, BUT the full casebook export opens fine. However attempting to open the export of the specific section the text block is in fails to open in Word: https://alpha.opencasebook.org/casebooks/68805-sam-contracts-for-testing/sections/4.3-unconscionability

The above is what i have found that've prevented successful export. Next I will compile what I can find regarding tags that cause annotation issues.

**Comment by bjohnson747** [comment]
I did extensive work to see if corrupt cases were causing #290 - I have not found that to be so. See that issue for my annotation findings.

I also explored the various cases sent by a user that they had trouble making elisions to; I found that instead of there being a specific set of case data/html issues causing their issues, there was a range of other causes for their problems over the past several months: issue #392, #364, #290, or simply an incomplete version of the case that had been originally ingested in H2O.

The one case-text issue I found was a case whose block-quotes were not showing up in new H2O, until they were opened in the case text editor, which put paragraph tags on the untagged paragraph. more details in #371.

**Comment by abziegler** [comment]
Content marked with <blockquote> tags does not appear in H2O (see #371)

**Comment by abziegler** [comment]
Content missing tags altogether does not appear in H2O

**Comment by cgruppioni** [comment]
3. 
new_content = new_content.gsub(/Appellant\\'s/, "Appellant\'s")
new_content = new_content.gsub(/appellant\\'s/, "appellant\'s")
new_content = new_content.gsub(/appellee\\'s/, "appellee\'s")

**Comment by cgruppioni** [comment]
Didn't find any cases with `<article>` or `<section>` tags. 

It seemed the issue for this case was that there were slashes in front of apostrophes in blockquotes
