### ISSUE TITLE
Default labeling for sections is confusing

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#323]
Sections aren't being numbered relative to how many other sections there are but how many items are in the given section.

I created, in this order, a text resource, a section, a link resouce, and a section. 
The sections auto-numbered to Section Two and Section Four, respectively, which is confusing:
<img width="874" alt="funky section numbering" src="https://user-images.githubusercontent.com/12850389/39643123-af87fad4-4fa1-11e8-925d-003c9c7684e8.png">

They should be auto-numbering to Section One and Section Two
Examples from: https://alpha.opencasebook.org/casebooks/57037-brand-new-casebook/layout

**Comment by abziegler** [comment]
It appears the Section numbers (1, 2, 3, etc.) are all correct, but the section labels ("Section One", "Section Two", etc.) is off b/c that default label text is inferring from the hierarchy.

Simplest approach to resolving this might be simply to always use a default section label of "Untitled Section" rather than a label that reflects hierarchy.
