### ISSUE TITLE
Can't drag item to the bottom of a casebook if bottom item is a section

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#326]
Can't drag an item to the base of a casebook, if its bottom item is a section - it automatically tries to put it in the section that's at the bottom.

Want to bring item 'New Link' to the bottom:
<img width="866" alt="moving item" src="https://user-images.githubusercontent.com/12850389/39645939-d4fc8b58-4fa7-11e8-8ceb-37988e536d24.png">

Attempting to (I can see it's going to put it into the section b/c of blue bar on the side):
<img width="866" alt="attempt" src="https://user-images.githubusercontent.com/12850389/39645953-dfa35898-4fa7-11e8-825e-39ed7f4a8f02.png">

Forces me to put it inside the section:
<img width="849" alt="automatically put inside section" src="https://user-images.githubusercontent.com/12850389/39645984-f482db4e-4fa7-11e8-974b-a32f6ef4377e.png">

**Comment by cgruppioni** [comment]
I don't think this is an issue still, but will test on staging once #526 is merged in

**Comment by cgruppioni** [comment]
**Objective: A user can drag a resource to the bottom of the casebook when the last piece of content in the table of contents in a section. Now the resource is forced to live inside the last section**

There is a functional workaround right now. If you put the resource above the section ( so that they are on the same level ) and then move the section above the resource, the resource becomes the last content in the table of contents and is not forced to nest underneath the section. 

**To fix this issue** either wait for the table of contents to be rewritten with Vue or begin by investigating this function `/app/assets/javascripts/lib/ui/content/dragging.js.erb`
