### ISSUE TITLE
Opening multiple resources in rapid succession causes a 500 error

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#332]
I when I open multiple items in a row quickly in new browser tabs, one or two will sometimes return a standard 500 error instead of the resource i've attempted to open.

<img width="548" alt="500 error" src="https://user-images.githubusercontent.com/12850389/39773600-9758f030-52c6-11e8-9c55-a105e582dc8e.png">

6 tabs loading at once

**Comment by bensteinberg** [comment]
This is due to a Solr exception: "Error opening new searcher. exceeded limit of maxWarmingSearchers=2, try again later." See discussion at https://wiki.apache.org/solr/FAQ#What_does_.22exceeded_limit_of_maxWarmingSearchers.3DX.22_mean.3F including "If you only encounter this error infrequently because of fluke situations, you'll probably be ok just ignoring it."

**Comment by cgruppioni** [comment]
Verified 7/25/19 - this isn't happening anymore
