### ISSUE TITLE
Odd behavior when applying focus styles to search results list

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/h2o#353]
I cannot get rid of those two weird empty boxes that appear when I try to apply the usual focus styling! I can't figure out what they are: they are not true elements, so must be ::before and ::after, but I'm not having any luck getting rid of it....

So, no focus styles for this list just yet. 

![image](https://user-images.githubusercontent.com/11020492/40445201-715d7606-5e99-11e8-8934-c4a24480003b.png)

**Comment by cgruppioni** [comment]
Conversation Becky and I had: 

I asked about the blue boxes seen when tabbing through search results and if that meant that this issue was fixed. 
ie: 
<img width="1380" alt="Screen Shot 2019-07-23 at 4 46 23 PM" src="https://user-images.githubusercontent.com/14900328/61748256-d1897d80-ad6d-11e9-9418-4f3a83b1c462.png">

She said no: 
The blue thing you are seeing there is the `:focus` style applied by default by Chrome. It's pretty good! But browsers are all different, and lots of them are very hard to see: check it out in Firefox, for instance. And, some of H2O's elements are fancy: not buttons, everywhere it looks like a button, and links, everywhere it looks like a link. Some of the visual buttons are actually `<a>` tags, etc. So, the browser's default `:focus` styling wasn't getting applied. And, lots of designers like to choose how `:focus` looks.

So, we have `@include generic-focus-styles;`, https://github.com/harvard-lil/h2o/blob/fe338b03f1fb42c034b8fa4a41e15fb3092636be/app/assets/stylesheets/mixins.scss#L45, which give the nice gray box that Dano picked as a focus style, like when you tab to any of the elements in the main header.

For consistency, that should be the `:focus` style everywhere.
But, it doesn't work right in the results list, like the screenshot in the ticket.

**Comment by holtchesley** [comment]
Addressed in #1104
