### ISSUE TITLE
Handle annotation breakage caused by case edits

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#503]
H2O admins can edit cases through the Rails Admin. This might happen when there's an error in a case (e.g. OCR errors from CAPAPI). When cases are edited however, there's a possibility those edits break/mess up annotations of those cases.

We should, maybe:

1. Recalculate and adjust annotation locations automatically whenever changes are made to a case
2. Give H2O admins a way to check/confirm/correct affected annotations

Or find a different/better solution. It's certain that we'll need to edit/improve cases. It's certain that we'll foul annotations as a result. It's certain that we should have some way to detect and correct fouled annotations.

**Comment by leppert** [comment]
Once we've merged CAPAPI import, we should also consider the impact there. In that branch, I'm storing the CAPAPI id for each imported case with the idea that, as CAPAPI improves their own data, cases can periodically pull updates and refresh their cache of that data. There are two challenges here:

1. We don't want to blow away any manual edits that have been made to cases
2. We don't want to break annotations

Number 2 is essentially just a variation on the primary topic of this ticket. Number 1 might require thinking about where edits should actually be made. Would it be better for CAPAPI data to be improved and for that to trickle down to everyone rather than have H2O start to fork from CAPAPI as a data source?

**Comment by abziegler** [comment]
@jcushman and I were chewing on this earlier. There's complication all around. In a perfect world, data corrections would be made in CAPAPI and could be published out and consumed from there, but that's a lot of complexity that CAPAPI isn't quite ready for.
