### ISSUE TITLE
Merge / Test / Deploy Instructions - Week of 8.20.18

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#510]
Currently on stage are PRs #500, #502, #506, #509 - @bjohnson747  should test these thoroughly as soon as he gets back. When testing is done, @bensteinberg should deploy to production.

Currently pending is PR https://github.com/harvard-lil/h2o/pull/501 - This is Greg's CAPAPI integration work, which @cgruppioni and I have both reviewed/tested locally and feel good about. @bensteinberg you should merge this and deploy to stage. @bjohnson747 you should use it, play with it, test it extensively, aggressively, maniacally, mercilessly - write down every little thing that seems weird, confusing or not quite right. 

Week of 8.27.18 we'll go over Brett's notes and assess before deploying to production. @bensteinberg you should not deploy the CAPAPI stuff to production until we're all back and ready.

**Comment by cgruppioni** [comment]
Note: There are a handful of issues in the "Done" column that are not closed. This is because they currently in staging and not deployed to production. There are also a couple data manipulation tickets that I need to run, but I'm waiting until all of the cap api stuff is out of staging -- because so much is going on in staging right now.
