### ISSUE TITLE
Cases that are encompassed in a <div> tag only show as having 1 paragraph

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#617]
Cases that have `<div>` tags at their beginning and end don't let me annotate beyond a single paragraph, for example: https://opencasebook.org/admin/case/1992/edit

**Comment by rebeccacremona** [comment]
@rebeccacremona todo tomorrow: is this still true? https://github.com/harvard-lil/h2o/issues/617. if yes in prod, be sure to check w/global offset PR. I am pretty positivie I saw these were fine, during my testing: checked lots of cases enclosed in a single div, though did not create any new annotations

**Comment by rebeccacremona** [comment]
Double-checked with McBoyle v. United States, as per screenshot above: annotating seems fine, anywhere in the text.

If we want, after #812 is live, we can remove these `<div>`s so that more on-the-fly paragraph numbers are generated. FWIW: there are 199 cases with `<div>`s, only 29 of which are annotated. Of the 29 annotated, almost all contain just a single wrapper div, like this; I imagine the other 170 are similar.

**Comment by rebeccacremona** [comment]
Update: we can definitely just remove these divs now.
