### ISSUE TITLE
H2O parsing <summary> tags from CAPAPI into <aside> tags

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#690]
Some CAP cases (esp. old SCOTUS cases, e.g. https://api.case.law/v1/cases/1421263/?full_case=true&body_format=xml) have `<summary>` tags. On ingest, H2O is parsing these into `<aside>` tags rather than `<p>` tags. As a result the content of the tags is not rendering at all.

These likely should be parsed as `<p>` tags, probably with `class='summary'`

**Comment by abziegler** [comment]
Requires more research in CAP

**Comment by leppert** [comment]
FYI that if they were being brought in as `<summary>` tags, they'd also be filtered out by the front-end JS due to the fact that I excluded it from the list of valid tags here: https://github.com/harvard-lil/h2o/blob/master/app/webpacker/libs/html_helpers.js#L52

This whitelist is meant to prevent HTML elements from being rendered to the page that have no utility for text based resources but which could create problems with the site (imagine an `<applet>` tag, for instance). Because `<summary>` is defined as an [interactive element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element#Interactive_elements), I excluded it from that whitelist.

**Comment by abziegler** [comment]
Thanks. Looks like CAPAPI's HTML format supplies them as `<aside class='summary'>`. `<aside>` is on the whitelist but the text inside the tag is not rendering still.

For example, in this case - https://opencasebook.org/casebooks/128913-untitled-casebook-128913/resources/1-gibbons-appellant-v-ogden-respondent - compare para 36 (ingested html is `<aside>` rather than `<p>`) with paras 35 and 37

**Comment by leppert** [comment]
It looks like I added a method to deliberately unnest those tags in the Ruby:
https://github.com/harvard-lil/h2o/blob/master/lib/html_helpers.rb#L8-L13

Which I then ported over to Vue / JS:
https://github.com/harvard-lil/h2o/blob/master/app/webpacker/libs/html_helpers.js#L27-L30

Can't remember why (I'm sure the reason was a good one at the time) but removing those tags from that method or removing the method invocation entirely would allow them to be rendered.
