### ISSUE TITLE
Can't edit notes 

### ISSUE THREAD

**Issue by cgruppioni** [harvard-lil/h2o#691]
Was initially added in #460

**Comment by abziegler** [comment]
On both FF and Chrome, the edit link form displays partially off-screen: 
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/2140548/75188732-ab202c00-571a-11ea-891d-34e74ee4738d.png">

The edit-note form does not display off-screen:

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/2140548/75188797-d30f8f80-571a-11ea-8cd5-1ddbc5b19a1f.png">

**Comment by abziegler** [comment]
Another small bug here, that shows up when adding multiple notes to visible text. Confirmed on FF and Chrome. The notes appear to stack on top of each other rather than tether to the note location and clip-icon:

![image](https://user-images.githubusercontent.com/2140548/75262641-d195a400-57ba-11ea-9576-b67194c84667.png)
