### ISSUE TITLE
Link Annotation across formatted text splits into multiple links

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#728]
When Add Link annotation includes text that's formatting in more than one way, the link-icon shows up once per kind of formatted text. (This should make it clearer what I mean): 

Add Link annotation applied to some italicized text, and not-italicized:
![Screen Shot 2019-04-01 at 3 10 41 PM](https://user-images.githubusercontent.com/12850389/55353187-ae6e5180-5490-11e9-9c64-2f1e8406ccce.png)

Shows Two separate links:
![Screen Shot 2019-04-01 at 3 10 49 PM](https://user-images.githubusercontent.com/12850389/55353199-b3330580-5490-11e9-8134-d2c44f956202.png)

Note this appears to only happen when it includes *part* of the specially formatted text. When the entire italicized text is selected, it correctly shows only one link icon:
![Screen Shot 2019-04-01 at 3 11 05 PM](https://user-images.githubusercontent.com/12850389/55353229-c940c600-5490-11e9-8254-d26bfa3abd5c.png)

**Comment by leppert** [comment]
This can be fixed by adding a `tail` class as we do here:
https://github.com/harvard-lil/h2o/blob/master/app/webpacker/components/ReplacementAnnotation.vue#L3

And then scoping this css within that `tail` class:
https://github.com/harvard-lil/h2o/blob/master/app/webpacker/components/LinkAnnotation.vue#L106-L111
