### ISSUE TITLE
Investigate pandoc as possible replacement to htmltodoc

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#776]

**Comment by rebeccacremona** [comment]
So far, this experiment is going quite well: from neatly-formatted markdown, I can recreate the docx for an existing annotated casebook entirely intact, with no pandoc customizations... except for the beautifully formatted Table of Contents currently being produced by the xslt. (I can produce the terrible default Table of Contents, the same one you get if you open a current H2O casebook DOCX and select "update entire table" instead of "update page numbers only". It's not a deal breaker: it should be possible to recreate the superior Table of Contents + accompanying bookmarks using pandox filters.

**Comment by rebeccacremona** [comment]
TOC section
![image](https://user-images.githubusercontent.com/11020492/57408862-cf734200-71b4-11e9-96e3-05155aa847c3.png)
Most deeply nested section, with breadcrumbs (bookmarks)
![image](https://user-images.githubusercontent.com/11020492/57408889-e154e500-71b4-11e9-9283-0550206711ef.png)

**Comment by cgruppioni** [comment]
Tagged some things as pandoc https://github.com/harvard-lil/h2o/issues?q=is%3Aissue+is%3Aopen+label%3Apandoc that may or may not be relevant. Feel free to untag things that are not relevant

**Comment by abziegler** [comment]
Closing this because we're beyond investigation at this point
