### ISSUE TITLE
Case search weirdness

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#811]
Searching for a CAP case that is in H2O - searching by name didn't pull up case, but citation did:.

failed:
![Screen Shot 2019-06-04 at 1 34 28 PM](https://user-images.githubusercontent.com/12850389/58900727-b5eaea80-86cd-11e9-9551-ae8a1cf39b68.png)

worked:
![Screen Shot 2019-06-04 at 1 34 57 PM](https://user-images.githubusercontent.com/12850389/58900729-b71c1780-86cd-11e9-91ca-ca1ead4b5223.png)

**Comment by cgruppioni** [comment]
@bjohnson747 Are you sure this case was already in the database? Was it used in another casebook? I only see 1 copy of this case in the db

**Comment by bjohnson747** [comment]
@cgruppioni yeah, it was already in the DB - looks like it was added on May 28th

**Comment by cgruppioni** [comment]
@bjohnson747 Ok did you pull it in through cap? Because I see only 1 case with that name abbreviation in the db and it does show up for me when I search for it 

<img width="698" alt="Screen Shot 2019-06-07 at 2 39 07 PM" src="https://user-images.githubusercontent.com/14900328/59126036-0bbfcc80-8932-11e9-8b34-6593d5d65690.png">

**Comment by rebeccacremona** [comment]
Cannot reproduce.
