### ISSUE TITLE
Staging Testing Plan 6/10

### ISSUE THREAD

**Issue by cgruppioni** [harvard-lil/h2o#814]
Staging to Prod diff: https://github.com/harvard-lil/h2o/compare/v20190516-01...master

Testing plan: 
- [x] Clicking through search ( page 1, 2 of casebook search results ) does not lose filtering ( sorting by date)
- [x] Private cases can not be adde to casebooks 
- [ ] Previously if you put in the citation for a private case, that case gets added as a resource, rather than pulled from CAP
- [x] Sort casebook & case results by date and alphabetical order work 
- [x] When switching tabs ( casebooks, cases, users ) the count on each tab remains the same https://github.com/harvard-lil/h2o/issues/712
- [x] On user tab, the author casebook count should only be for published casebooks
- [x] The export modal no longer says “Confirm Publish” in the title, it says “Export Casebook”

--------------------------------------------------------------------------------------
Note for Casey: when deploying to Prod run these queries: 
https://github.com/harvard-lil/h2o/issues/804

**Comment by bjohnson747** [comment]
@cgruppioni all looked good besides checkbox #3, some notes on that:

I tested the step as written, with a non-CAP case: I set it to private, searched for it by citation, and instead of adding the exsting non-CAP case it added the CAP case to the DB. <-looks good. However, i then tried setting an existing CAP case to private... see below:

-I set an existing CAP case in the DB to private (Walker v Keith, case #8435)
-Did Add Resource -> searched by name, didn’t pull the case up. (correct so far)
-Searched via Add Resource by case citation: it pulled it from CAP because the existing CAP case in the DB was set to private. Then added it to the casebook (and DB). The CAP case is now in the DB twice.

I think we shouldn't allow the case to be added again from CAP if the CAP case that already exists in the DB has been set to private. (I can’t think of any use cases where we’d set a CAP case to private.)

I think if a CAP case has been set to private, and a user tries to add it again by citation, it should refuse to add it, maybe they should get a message saying “there’s been an error trying to add this case, please contact H2O support at info@opencasebook.org for more information.”

In the immediate term, if you want to deploy this, one option could be: IF CAP case existing in DB is set to private, set it so users can't add the CAP case again to the DB (Add Resource just returns "Case not found.") - Then in the near future we can add the above error message, or something similar.

---

**Comment by bjohnson747** [comment]
Separately, when I try to delete the extra versions of Walker v Keith, it says the following, even though it's not actually in these other casebooks:

![Screen Shot 2019-06-11 at 11 35 10 AM](https://user-images.githubusercontent.com/12850389/59289084-3ddb7200-8c43-11e9-9484-9418633845d8.png)

**Comment by cgruppioni** [comment]
@bjohnson747 re: a CAP case is set to private and then the next `add resource` search downloads another copy of the case from CAP

I actually think this is intended behavior because the nature of a private case is that it’s edited for a specific casebook and we don’t want other people to use it - so we would want another copy re-downloaded

**Comment by cgruppioni** [comment]
> Separately, when I try to delete the extra versions of Walker v Keith, it says the following, even though it's not actually in these other casebooks:
> 
> ![Screen Shot 2019-06-11 at 11 35 10 AM](https://user-images.githubusercontent.com/12850389/59289084-3ddb7200-8c43-11e9-9484-9418633845d8.png)

I looked at the 3 copies of this case in staging 
https://h2o-dev-test.lil.tools/admin/case/8438/edit
https://h2o-dev-test.lil.tools/admin/case/8437/edit
https://h2o-dev-test.lil.tools/admin/case/8435/edit

and didn't see those casebook links. Were you looking somewhere else?

**Comment by bjohnson747** [comment]
@cgruppioni may've gotten mixed up with the live site, lemme double check!

**Comment by bjohnson747** [comment]
@cgruppioni found it - for example, the 2nd Walker v Keith I added: https://h2o-dev-test.lil.tools/admin/case/8437/edit

It doesn't say it at the bottom of the case Edit page: 
![Screen Shot 2019-06-13 at 1 46 02 PM](https://user-images.githubusercontent.com/12850389/59455193-ac563680-8de1-11e9-9699-aad369e32bb3.png)

But when I click the Delete button it shows that: 

![Screen Shot 2019-06-13 at 1 46 11 PM](https://user-images.githubusercontent.com/12850389/59455208-b415db00-8de1-11e9-94ec-8fee1e5f4829.png)
