### ISSUE TITLE
Missing note annotation

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#840]
Appear to have lost a note-style annotation on experiment site

Prod - see para 183 - 2 notes - https://opencasebook.org/casebooks/79342-corporations/resources/5.3.3-u-s-v-general-motors#/

![image](https://user-images.githubusercontent.com/2140548/62074032-e489cb00-b20f-11e9-86dd-f757d15d9067.png)

Experiment - see para 183 - 1 note - https://h2o-experiment.lil.tools/casebooks/79342-corporations/resources/5.3.3-u-s-v-general-motors#/

![image](https://user-images.githubusercontent.com/2140548/62074050-f10e2380-b20f-11e9-9e72-502854a7f14f.png)

**Comment by rebeccacremona** [comment]
In old H2O
![image](https://user-images.githubusercontent.com/11020492/62149985-e9f81b80-b2ca-11e9-951e-ffc35502c468.png)

**Comment by rebeccacremona** [comment]
Okay, if this is indeed the same casebook, and I'm pretty sure it is... https://h2o.law.harvard.edu/collages/41498... annotations differ VERY substantially between old h2o and current prod. It's totally messed up, elisions, notes, and all.

Old H2O displays 6 notes, in this order:
- [Product Investigations]
- [Investigation Status Review]
- [Field Performance Evaluation]
- [FPE Team]
- [FPE Review Committee]
- [Executive Field Action Decision Committee]

Our post-migration DB contains 7 note annotations.

Prod displays only 2. Experiment displays only 3, and they are different. Both prod and experiment show everything in different spots than old h2o. And, both prod and experiment show a wonky "[weekly]" replacement, similar but not identical to the "weekly" note in the database (not rendered in the browser on either branch) (... and there is no [weekly] note or replacement in old h2o).

So, I think we can safely conclude that all the problems we are seeing here predate the `experiment`. Further diagnosis is beyond me at the moment. See #841 and [this discussion](https://github.com/harvard-lil/h2o/pull/812#issuecomment-511466828) for a discussion about similar situations.

**Comment by abziegler** [comment]
Lots of work on the casebook since migration from old H2O. I'd be hesitant to rely on old H2O for truth, especially for casebooks that have been actively edited/updated since we moved. Should concern be with the variance between prod and experiment (which has prod data as of last week)?

**Comment by rebeccacremona** [comment]
Oh yes, for sure! 

But it's definitely the case that some annotations are wonky on prod, and they are just differently wonky on experiment. If you saw Greg's diagnosis of #841, he describes an annotation that doesn't appear in prod but appears in experiment, and explains why, with an analysis of the offsets (see "Production, however, renders nothing because it stays within paragraph 7 looking for offsets that don't exist."). I haven't done a detailed analysis of the offsets here, but it sounds like the very same mechanism.

Even knowing this book has received substantial attention post-migration, it seems unlikely to me that the 5 "hidden"/not-rendered note annotations are absent on purpose, and that the 2 that are rendered are in the intended spot. It seems more likely that this is another instance of "annotation drift prior to the experiment branch, likely due to changes in the way the paragraphs were processed."
