### ISSUE TITLE
Annotation drift on text resource

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#841]
Elision on prod is showing as weird double-elision on experiment. This is a text resource (a statutory provision). 

Prod - see para 10 - https://opencasebook.org/casebooks/72837-an-introduction-to-the-law-of-corporations-cases-and-materials/resources/2.2.5-dgcl-sec-103-filing-requirements#/

![image](https://user-images.githubusercontent.com/2140548/62137424-ec02b000-b2b3-11e9-9f18-5cfc7a784712.png)

Experiment - see para 10 - https://h2o-experiment.lil.tools/casebooks/72837-an-introduction-to-the-law-of-corporations-cases-and-materials/resources/2.2.5-dgcl-sec-103-filing-requirements#/

![image](https://user-images.githubusercontent.com/2140548/62137394-e1481b00-b2b3-11e9-99dc-40129b928505.png)

**Comment by leppert** [comment]
This appears to be due to annotation drift prior the `experiment` branch, likely due to changes in the way the paragraphs were processed. (See [here](https://github.com/harvard-lil/h2o/pull/812#issuecomment-511466828) for a similar issue).

In this case, of the two elisions that are rendered in paragraph 10 on `experiment`, the first looks like this in the production JSON:

```json
{
    "id": 401634,
    "resource_id": 72869,
    "start_paragraph": 7,
    "end_paragraph": 7,
    "start_offset": 368,
    "end_offset": 1118,
    "kind": "elide",
    "content": " [#285703]",
    "created_at": "2018-07-05T15:41:22.149-04:00",
    "updated_at": "2018-07-05T15:41:22.149-04:00"
}
```

Notice the `start_offset=368`. If we look at that paragraph on production, here's the entirety of it:

> d. By the holders of record of all outstanding shares of stock.

So what `experiment` did was start at paragraph `7` and move forward `368` characters, which puts it right there as we see it in paragraph `9' (or "paragraph 10" if going from index 1 instead of index 0). Production, however, renders nothing because it stays within paragraph 7 looking for offsets that don't exist.

For possible solutions, I'll refer back to that earlier comment [here](https://github.com/harvard-lil/h2o/pull/812#issuecomment-511466828).
