### ISSUE TITLE
De-link page numbers in export

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#993]
Case page numbers are linked in-browser, which is correct, but we don't want link effect/styling in the export. We need a default export styling that signifies in-case page number.

**Comment by rebeccacremona** [comment]
If the links worked in the docx instead of being broken, would this still be wrong? If the links can be made to work, shall we keep them, independent of how they look? If it's "correct" in browser, seems like it would be equally desirable in an export too. The appearance in an exported can (I think?) be tweaked as desired either way.

**Comment by rebeccacremona** [comment]
See related https://github.com/harvard-lil/h2o/issues/692

**Comment by abziegler** [comment]
I'm not sure what it would mean for the pagenumber-links to "work" in docx. On the web, these in-page links are useful if you want to send someone to a particular part of a doc. In a docx, the links can't serve that function, I don't think. I could be missing the point...
